### ISSUE TITLE
Is it intentional that the linux temurin builds for amd64 are using musl?

### ISSUE THREAD

**Issue by jeffhertzler** [Jabba-Team/index-generator#10]
I would have expected a separate section for alpine that uses the musl versions but not for standard linux. It can be worked around by using a direct adoptium URL. Just wanted to double-check this was on purpose and not an oversight.

**Comment by patrick-mccourt** [comment]
Hi @jeffhertzler 

Thank you for flagging this, this looks like there's a bug with our Index generator. Looking at the [DiscoAPI response here](https://api.foojay.io/disco/v3.0/packages?jdk_version=19&distro=temurin&architecture=amd64&operating_system=linux&package_type=jdk) for linux, amd64, temurin, the response body contains musl & glibc packages.

I don't think the DiscoAPI response is ordered but in the cases where you've found musl versions being installed, the musl version is processed most recently. i.e. temurin 19.0.2+7 is found, it's standard linux package and it's added. Then the next record in the Disco response is temurin 19.0.2+7, but the musl version and the index processor just replaces the previous one. 

Will take a look

**Comment by patrick-mccourt** [comment]
Hi again, I have changed the index-generator to exclude the musl builds for now to ensure the standard package is always used. 

I'm not sure jabba even works on alpine but we can test that and update the index generator to separate out to better support it

**Comment by jeffhertzler** [comment]
awesome thanks!
